sudo: false
language: php

php:
  - 7.3
  - 7.4
  - nightly
  - hhvm

cache:
  directories:
    - ~/.composer/cache

before_script:
  - composer self-update
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require --no-update symfony/config:${SYMFONY_VERSION} symfony/dependency-injection:${SYMFONY_VERSION} symfony/event-dispatcher:${SYMFONY_VERSION} symfony/http-kernel:${SYMFONY_VERSION} symfony/framework-bundle:${SYMFONY_VERSION}; fi;
  - if [ "$SYMFONY_EVENT_DISPATCHER_VERSION" != "" ]; then composer require --no-update symfony/event-dispatcher:${SYMFONY_EVENT_DISPATCHER_VERSION}; fi;
  - composer install --no-interaction --prefer-source --dev

script: vendor/bin/phpunit --verbose

matrix:
  include:
    - php: 7.3
      env: [SYMFONY_VERSION="^4.4", SYMFONY_EVENT_DISPATCHER_VERSION="^4.4"]
    - php: 7.3
      env: [SYMFONY_VERSION="^5.0", SYMFONY_EVENT_DISPATCHER_VERSION="^5.0"]

    - php: 7.4
      env: [SYMFONY_VERSION="^4.4", SYMFONY_EVENT_DISPATCHER_VERSION="^4.4"]
    - php: 7.4
      env: [SYMFONY_VERSION="^5.0", SYMFONY_EVENT_DISPATCHER_VERSION="^5.0"]

  allow_failures:
    - php: nightly
    - php: hhvm
  fast_finish: true
